spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: test-group
      enable-auto-commit: false
    topic:
      name: test-topic
      partitions: 3
      replication-factor: 1

message:
  file-path: src/main/resources/random-people-data.json